// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KongaTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void passwordlessthan6characters() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1666, 1069));
    driver.findElement(By.linkText("Login / Signup")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("fayemisimisola@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("hops");
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_988cf_1aDdJ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_71d30_2oCCX")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(4)")).getText(), is("The password must be at least 6 characters"));
    driver.findElement(By.cssSelector(".\\_40e43_1f83p > svg")).click();
    driver.close();
  }
  @Test
  public void wrongusernamepassword() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1666, 1069));
    {
      WebElement element = driver.findElement(By.linkText("Login / Signup"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Login / Signup")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("fayemos@gmail.com");
    driver.findElement(By.id("password")).sendKeys("HopHop24");
    driver.findElement(By.cssSelector(".\\_988cf_1aDdJ")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_988cf_1aDdJ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_71d30_2oCCX")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9a1ab_k0UMi:nth-child(3)")).getText(), is("The username or password you have entered is incorrect. Please try again."));
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_988cf_1aDdJ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Close")).click();
    driver.close();
  }
  @Test
  public void verifyHomePageLoad() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1667, 1069));
    driver.findElement(By.cssSelector(".\\_40d77_2fZbm")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".\\_8486b_25fFV")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".\\_63857_1TmYU:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_486fd_2lQ2Q path")).click();
    driver.findElement(By.cssSelector(".\\_486fd_2lQ2Q path")).click();
    driver.findElement(By.cssSelector(".\\_486fd_2lQ2Q path")).click();
    driver.findElement(By.cssSelector(".\\_279e8_sHZep use:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".\\_279e8_sHZep use:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_279e8_sHZep use:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_279e8_sHZep use:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".\\_279e8_sHZep use:nth-child(2)")).click();
  }
  @Test
  public void verifyProductDetailPage() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1667, 1069));
    driver.findElement(By.cssSelector(".f6ed2_25oVd #jsSearchInput")).click();
    driver.findElement(By.cssSelector(".f6ed2_25oVd #jsSearchInput")).sendKeys("smartphone");
    driver.findElement(By.cssSelector(".f6ed2_25oVd #jsSearchInput")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,301)");
    driver.findElement(By.cssSelector(".bbe45_3oExY:nth-child(1) .f5e10_VzEXF")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".\\_24849_2Ymhg")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > h3")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > .a-list-item")).click();
  }
  @Test
  public void verifySearchFunctionality() {
    driver.get("https://www.konga.com/");
    driver.manage().window().setSize(new Dimension(1667, 1069));
    driver.findElement(By.cssSelector(".f6ed2_25oVd #jsSearchInput")).click();
    driver.findElement(By.cssSelector(".f6ed2_25oVd #jsSearchInput")).sendKeys("laptop");
    {
      WebElement element = driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".f6ed2_25oVd > .fdd83_39Iap > svg")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_9590c_10MV8")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_9590c_10MV8")).getText(), is("Search Results - Laptop"));
  }
  @Test
  public void verifyUserCannotResetPasswordWithInvalidEmailFunctionality() {
    driver.get("https://www.konga.com/search?search=");
    driver.manage().window().setSize(new Dimension(1710, 1069));
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.linkText("Logout")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("Login / Signup")).click();
    driver.findElement(By.linkText("Forgot Password?")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fayemisimisola@gmail.com");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fayemisimisa@gmail.com");
    driver.findElement(By.cssSelector(".fd68f_3wAfg")).click();
    driver.findElement(By.cssSelector(".\\_869ee_1ewC4")).click();
    assertThat(driver.findElement(By.cssSelector(".e2c5a_3U4MA")).getText(), is("We could not initiate password reset for your email: fayemisimisa@gmail.com. Please check that the address is valid and try again"));
    driver.findElement(By.cssSelector(".bf973_YytIl")).click();
    driver.close();
  }
}
